name: blogit
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.4
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^2.4.4
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  provider: ^6.1.2
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
