// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyLC_dNYS-77BLF2yrMQvijEabq3gRNuk',
    appId: '1:707498132798:android:87bd9c9436b04a584f986f',
    messagingSenderId: '707498132798',
    projectId: 'blog-app-d2970',
    storageBucket: 'blog-app-d2970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-v5rSzPBFxLvPk5d3zA1dSL8a_crgDkY',
    appId: '1:707498132798:ios:f3ccbc67f05e1bcb4f986f',
    messagingSenderId: '707498132798',
    projectId: 'blog-app-d2970',
    storageBucket: 'blog-app-d2970.firebasestorage.app',
    iosBundleId: 'com.example.blogit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASHBLCy19K48kQFqAylpBL49QGHqkuwyk',
    appId: '1:707498132798:web:4208461c514ff98f4f986f',
    messagingSenderId: '707498132798',
    projectId: 'blog-app-d2970',
    authDomain: 'blog-app-d2970.firebaseapp.com',
    storageBucket: 'blog-app-d2970.firebasestorage.app',
  );
}
